/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.krismorte.menuutil.view;

import com.github.krismorte.menuutil.MenuBarra;
import com.github.krismorte.menuutil.dao.MenuBarraDao;
import com.github.krismorte.menuutil.interfaces.iAtualizaGUI;
import com.github.krismorte.menuutil.util.InspectorUtil;
import com.github.krismorte.menuutil.util.PopupMenu;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
/**
 *
 * @author c007329
 */
public class MenuBarraCRUD extends javax.swing.JDialog implements iAtualizaGUI {

    private String[] colunas = {"ID", "Nome", "Principal"};
    private Object[][] linhas;
    private MenuBarraDao menuBarraDao;
    private List<MenuBarra> lista;
    private EntityManagerFactory emf;

    /**
     * Creates new form MenuBarra
     */
    public MenuBarraCRUD(java.awt.Frame parent, EntityManagerFactory emf) {
        super(parent, true);
        initComponents();
        this.emf = emf;
        menuBarraDao = new MenuBarraDao(MenuBarra.class, emf);
        preencheTabela();
        this.validate();
    }

    public void preencheLinhas(List<MenuBarra> list) {
        linhas = new Object[list.size()][colunas.length];
        if (list.size() > 0) {
            for (int i = 0; i < list.size(); i++) {
                for (int z = 0; z < colunas.length; z++) {
                    Object[][] obj = {{list.get(i).getId(), list.get(i), list.get(i).getPrincipal()}};
                    linhas[i][z] = obj[0][z];//Rows are dynamics
                }
            }
        }
    }

    private void preencheTabela() {
        lista = menuBarraDao.listAll();
        preencheLinhas(lista);

        panelBarras.removeAll();

        //panelBarras.add(InspectorUtil.jTableDecorator(panelBarras, colunas, linhas));
        panelBarras.add(InspectorUtil.jTableDecoratorWithMenuPopup(panelBarras, PopupMenu.getSimpleVersion(this, null, 1, emf), colunas, linhas));
        panelBarras.validate();
    }

    @Override
    public void atualizarTela() {
        preencheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMenuBarra = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        panelBarras = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Meny Bar");

        jLabel1.setText("Nome:");

        btnSalvar.setText("salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        panelBarras.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelBarrasLayout = new javax.swing.GroupLayout(panelBarras);
        panelBarras.setLayout(panelBarrasLayout);
        panelBarrasLayout.setHorizontalGroup(
            panelBarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelBarrasLayout.setVerticalGroup(
            panelBarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMenuBarra))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 295, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMenuBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!txtMenuBarra.getText().equals("")) {
            if (lista.isEmpty()) {
                criaMenuBarra(txtMenuBarra.getText(), true);
                inicializaTela();
            } else {
                if (!InspectorUtil.existingName(lista, txtMenuBarra.getText())) {
                    criaMenuBarra(txtMenuBarra.getText(), false);
                    inicializaTela();
                } else {
                    JOptionPane.showMessageDialog(null, "Nome já existe!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite um nome!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void criaMenuBarra(String texto, boolean principal) {
        MenuBarra menuBarra = new MenuBarra();
        menuBarra.setNome(texto);
        menuBarra.setPrincipal(principal);

        menuBarraDao.save(menuBarra);
    }

    private void inicializaTela() {
        txtMenuBarra.setText("");
        preencheTabela();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBarraCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBarraCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBarraCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBarraCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuBarraCRUD dialog = new MenuBarraCRUD(new javax.swing.JFrame(), null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelBarras;
    private javax.swing.JTextField txtMenuBarra;
    // End of variables declaration//GEN-END:variables
}
